server:
  port: 8088

  servlet:
    context-path: /api/v1.0.0

spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 50MB

springdoc:
  default-produces-media-type: application/json

  main:
    allow-circular-references: true